# Generated by Django 5.1 on 2024-09-15 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Supplier creation', 'Supplier creation'), ('PO creation', 'PO creation'), ('NDA', 'NDA'), ('Other request', 'Other request'), ('Supplier assist', 'Supplier assist')], max_length=50)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Not Started', max_length=50)),
                ('request_status', models.CharField(choices=[('Created', 'Created'), ('Waiting Homologation Validation', 'Waiting Homologation Validation'), ('Homologation validated', 'Homologation validated'), ('Invitation to log done', 'Invitation to log done'), ('Waiting for Supplier completion', 'Waiting for Supplier completion'), ('Supplier info completed', 'Supplier info completed'), ('Waiting for SMD Validation', 'Waiting for SMD Validation'), ('SMD Validation Done', 'SMD Validation Done'), ('Supplier Assist Started', 'Supplier Assist Started'), ('Supplier Assist In Progress', 'Supplier Assist In Progress'), ('Supplier Assist Completed', 'Supplier Assist Completed')], max_length=100)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments_text', models.TextField(blank=True)),
                ('new_comments_text', models.TextField(blank=True, help_text='Add new comments here')),
                ('object_field', models.CharField(editable=False, max_length=255)),
                ('attachments', models.FileField(blank=True, upload_to='attachments/')),
                ('subject', models.CharField(blank=True, max_length=25)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.buyer')),
                ('entered_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker.request')),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.requester'),
        ),
    ]
